import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    // Brand & Global
    brandName: "Krishi Samadhan",
    tagline: "Smarter Decisions. Better Agriculture.",
    heroTitle1: "Smarter Decisions.",
    heroTitle2: "Better Agriculture.",
    heroTagline: "Better Insights. Better Decisions. Better Farming.",
    heroSubtitle: "From your soil to the sky, from crop health to market prices—we bring everything you need to make confident decisions and grow with confidence.",
    explorePlatform: "Explore Platform",
    learnMore: "Learn More",
    activeStream: "Active Stream",
    monitoringLocality: "Monitoring Locality",

    // Navigation
    home: "Home",
    features: "Features",
    howItWorks: "How It Works",
    dashboard: "Dashboard",
    login: "Sign In",
    register: "Create Account",
    logout: "Sign Out",
    backToHome: "Back to Home",
    locality: "Locality",
    profile: "Profile",

    // Dashboard Sidebar Items
    overview: "Overview",
    gisDashboard: "GIS Spatial Map",
    weatherMonitoring: "Weather Monitoring",
    satelliteMonitoring: "Satellite Monitoring",
    soilHealth: "Soil Health & Nutrients",
    pestSurveillance: "AI Pest Surveillance",
    govSchemes: "Government Schemes",
    marketIntelligence: "Market Intelligence",
    farmerAdvisory: "Farmer Advisory",

    // Page Titles & Descriptions
    dashTitle: "Unified Agriculture Dashboard",
    dashDesc: "Real-time telemetry and decision support for",
    weatherTitle: "Weather Monitoring",
    weatherDesc: "Real-time micrometeorology and 7-day agricultural forecasts for",
    soilTitle: "Soil Health & Nutrients",
    soilDesc: "Soil chemistry, macronutrients (NPK), moisture profile, and conditioning for",
    advisoryTitle: "Farmer Advisory & Decision Support",
    advisoryDesc: "Integrated multi-source intelligence converting telemetry into actionable agronomic decisions for",
    gisTitle: "GIS & Spatial Intelligence Dashboard",
    gisDesc: "Interactive agricultural mapping, spatial layers, and field telemetry for",
    satelliteTitle: "Satellite Monitoring & Vegetation Indices",
    satelliteDesc: "Multispectral telemetry, Normalized Difference Vegetation Index (NDVI), and canopy health for",
    pestTitle: "AI Crop Pest Surveillance & Pathology",
    pestDesc: "Deep learning crop image analysis for real-time disease detection and treatment plans.",
    schemesTitle: "Government Agricultural Schemes",
    schemesDesc: "Verified Central and Maharashtra State agricultural support programs, financial subsidies, and credit facilities.",
    marketTitle: "Market Intelligence & Agri Input Store",
    marketDesc: "Real-time APMC mandi commodity prices, nearby shop comparisons, and input price tracking.",

    // Weather & Metrics
    ambientConditions: "Current Ambient Conditions",
    humidity: "Relative Humidity",
    windSpeed: "Wind Speed",
    precipitation: "Precipitation",
    weatherCode: "Weather Code",
    synopticForecast: "7-Day Agricultural Synoptic Forecast",
    weatherSignals: "Automated Agricultural Weather Signals",
    sprayFavorable: "Spray Favorable: Wind speeds are gentle and no precipitation expected.",
    sprayWarning: "Spray Warning: High winds or rain detected, defer chemical spraying.",
    irrigationRecommended: "Irrigation Recommended: Low precipitation in past 24 hours.",
    soilMoistureSufficient: "Soil Moisture Sufficient: Defer heavy irrigation.",

    // Soil
    soilIndex: "Overall Soil Health Index",
    soilClassification: "Soil Classification",
    physicalProperties: "💧 Physical Properties",
    chemicalProperties: "⚗️ Chemical Properties",
    primaryNutrients: "🧪 Primary Nutrients (NPK)",
    organicCarbon: "Organic Carbon (SOC)",
    soilRecommendations: "Agronomic Soil Health Recommendations",
    nitrogen: "Nitrogen (Available N)",
    phosphorus: "Phosphorus (Available P)",
    potassium: "Potassium (Available K)",
    phLevel: "Soil pH Level",

    // Market & Store
    apmcRates: "APMC Mandi Rates",
    inputStore: "Agri Input Store",
    fertilizers: "Fertilizers",
    seeds: "Seeds",
    pesticides: "Pesticides",
    priceComparison: "Shop Price Comparison",
    minPrice: "Min Price",
    maxPrice: "Max Price",
    modalPrice: "Modal / Avg Price",

    // Advisories
    activeAdvisories: "Active Farm Advisories",
    rerunEngine: "🔄 Re-Run Advisory Engine",
    synthesizing: "⚙️ Synthesizing Rules...",
    highPriority: "High Priority",
    mediumPriority: "Medium Priority",
    lowPriority: "Low Priority",

    // Schemes
    searchSchemes: "Search by scheme name or benefit (e.g. Kisan, Solar, Drip, Tractor)...",
    allCategories: "All Categories",
    visitPortal: "Visit Portal ↗",
    benefits: "Benefits",
    eligibility: "Eligibility",

    // Pest
    uploadPhoto: "Upload Crop Leaf Photo",
    analyzeImage: "🔍 Analyze Leaf Pathology",
    pestDiagnosis: "AI Diagnostic Result",
    severity: "Severity Level",
    treatmentPlan: "Prescribed Treatment Plan",

    // Common
    temperature: "Temperature",
    soilMoisture: "Soil Moisture",
    cropHealth: "Crop Health",
    search: "Search",
    filter: "Filter",
    status: "Status",
    refresh: "Refresh",
    applyNow: "Visit Portal",
    loadingMsg: "Loading data...",
    retry: "Try Again",

    // GIS & Spatial Map
    gisDashboardHeader: "AGRI-SAMADHAN GIS DASHBOARD",
    gisSubTitle: "Interactive Farm Map • 7-Layer Spatial Intelligence for",
    gisArchitectureBtn: "7-Layer Architecture",
    activeAlertsCount: "3 Active Alerts",
    farmerLabel: "Farmer",
    locationCadastre: "Location & Cadastre",
    sync10m: "10m Sync",
    spatialMapLayers: "Spatial Map Layers",
    activeCount: "Active",
    layerFarmBoundaries: "Farm Boundaries",
    layerCropTypes: "Crop Types & Stage",
    layerSatelliteHealth: "Satellite NDVI Health",
    layerWaterCanals: "Water & Canals",
    layerRainfallRadar: "Rainfall Radar",
    layerSoilNutrients: "Soil Nutrients (NPK)",
    layerPestAlerts: "Pest Alert Hotspots",
    layerMandis: "APMC Mandis & Rates",
    layerIotSensors: "IoT Sensor Nodes",
    filterPlots: "Filter Plots",
    crop: "Crop",
    allCrops: "All Crops",
    riskLevel: "Risk Level",
    allRisks: "All Risks",
    highRisk: "High Risk",
    mediumRisk: "Medium Risk",
    lowRisk: "Low / Safe",
    surveyNo: "Survey No",
    owner: "Owner",
    area: "Area",
    acres: "Acres",
    ndviHealth: "NDVI Health",
    estimatedYield: "Est. Yield",
    agronomicDirective: "Agronomic Directive",
    aiAdvice: "AI Advice",
    sendAlertSms: "Send Alert SMS",
    stage: "Stage",
    waterSource: "Water Source",
    yieldForecast: "Yield Forecast",
    discharge: "Discharge",
    capacityYield: "Capacity/Yield",
    highSeverityHotspot: "High Severity Hotspot",
    distance: "Distance",
    liveTradingRates: "Live Trading Rates",
    soilMoisture10cm: "Soil Moisture (10cm)",
    soilTemp: "Soil Temp",
    leafWetness: "Leaf Wetness",
    solarBattery: "Solar Battery",
    lastPing: "Ping",
    farmCoreCenter: "Farm Core Center",
    clickReposition: "Click anywhere on map to reposition",
    spatialLegend: "Spatial Legend",
    legendHealthy: "Healthy Canopy (NDVI > 0.70)",
    legendModerate: "Moderate Stress / Onion Plots",
    legendHighRisk: "High Risk / Pest Outbreak Hotspot",
    legendCanal: "Active Irrigation Canal Network",
    baseMapSatellite: "🛰️ Satellite Imagery",
    baseMapStreet: "🗺️ Standard Street",
    baseMapTopo: "🏔️ Topographic",
    baseMapDark: "🌙 Dark Terrain",
    gisArchTitle: "7-Layer Agricultural GIS Architecture",
    gisArchSubtitle: "End-to-end telemetry flow from multi-sensor data sources to localized farmer action.",
    gisL1Title: "1. Data Sources",
    gisL1Desc: "Weather APIs (IMD/OpenMeteo) + Sentinel-2 Satellite (NDVI/EVI) + In-situ IoT Soil Sensors + Groundwater + Crop Telemetry + Mandi Rates + Govt Schemes.",
    gisL2Title: "2. Data Integration Layer",
    gisL2Desc: "ETL spatial engine, coordinate projection (EPSG:4326), sensor noise filtering, and multi-spectral raster harmonization.",
    gisL3Title: "3. GIS Layer",
    gisL3Desc: "Vector farm boundaries, cadastral Survey No indexing, irrigation canals, thermal layers, and APMC geo-tagging.",
    gisL4Title: "4. AI / Analytics Layer",
    gisL4Desc: "Crop Water Stress Index (CWSI), epidemiology pest propagation models, weather risk scoring, and yield forecasting algorithms.",
    gisL5Title: "5. Decision Support Layer",
    gisL5Desc: "Rule engine converting multi-source indices into ranked agronomic priorities and threshold triggers.",
    gisL6Title: "6. Farmer Advisory Layer",
    gisL6Desc: "Multilingual localization into English, Marathi (मराठी), and Hindi (हिंदी) with simple, actionable field instructions.",
    gisL7Title: "7. Dashboard & Alerts Layer",
    gisL7Desc: "Interactive Leaflet map, real-time alert center, SMS/WhatsApp dispatcher, and action pipeline execution.",
    closeExplorer: "Close Architecture Explorer",
    smsSentToast: "Alert SMS successfully dispatched to",

    // Satellite Monitoring
    satelliteLoading: "Processing satellite spectral imagery (Sentinel-2) for",
    satelliteError: "Failed to retrieve satellite observations.",
    livePass: "Live Pass",
    sentinelTelemetry: "Sentinel-2 Telemetry:",
    sentinelSub: "Surface reflectance derived over 10m spatial resolution across",
    ndviVigorIndex: "NDVI Vigor Index",
    canopyMoisture: "Canopy Moisture (NDWI)",
    cropStressRisk: "Crop Stress Risk",
    cloudCover: "Cloud Cover",
    adequateHydration: "Adequate Canopy Hydration",
    zeroThermalAnomalies: "Zero thermal anomalies",
    opticalClarity: "Optical Clarity Optimal",
    minimalOptimal: "Minimal (Optimal)",
    moderate: "Moderate",
    landCoverUse: "Land Cover & Land Use",
    activeCropland: "Active Cropland",
    treeCoverOrchards: "Tree Cover & Orchards",
    ruralSettlement: "Rural Settlement / Roads",
    farmPonds: "Farm Ponds / Irrigation Tanks",
    biomassTrend: "Biomass Trend & Agronomic Summary",
    photosyntheticBiomass: "+6.8% Photosynthetic Biomass",
    sensorInfo: "Sensor: Sentinel-2 MSI • Cloud-Free Tile",
    healthy: "Healthy",

    // Chatbot
    chatTitle: "Krishi AI Assistant",
    chatSubtitle: "Active Decision Support",
    chatPlaceholder: "Ask in English, मराठी or हिंदी...",
    chatLauncher: "Ask Krishi AI",
    chatGreeting: "Namaste! 🙏 I am Krishi AI, your Krishi Samadhan decision assistant. Ask me anything about weather, soil nutrients, pest treatments, mandi rates, or government schemes!",
    sugWeather: "🌦️ Local Weather",
    sugSoil: "🌱 Soil Fertilizer Guide",
    sugPest: "🐛 Pest Solution",
    sugMandi: "💰 Mandi Rates",
    sugSchemes: "🏛️ PM-Kisan Scheme"
  },

  mr: {
    // Brand & Global
    brandName: "कृषी समाधान",
    tagline: "हुशार निर्णय. समृद्ध शेती.",
    heroTitle1: "अचूक निर्णय.",
    heroTitle2: "समृद्ध शेती.",
    heroTagline: "उत्तम माहिती. अचूक निर्णय. समृद्ध शेती.",
    heroSubtitle: "मातीपासून आकाशापर्यंत, पिकांच्या आरोग्यापासून ते बाजारभावांपर्यंत — आत्मविश्वासाने योग्य निर्णय घेण्यासाठी आणि समृद्धीकडे वाटचाल करण्यासाठी आवश्यक सर्व माहिती एकाच ठिकाणी.",
    explorePlatform: "प्लॅटफॉर्म पहा",
    learnMore: "अधिक माहिती",
    activeStream: "थेट प्रवाह",
    monitoringLocality: "शेत परिसर",

    // Navigation
    home: "मुख्यपृष्ठ",
    features: "वैशिष्ट्ये",
    howItWorks: "कसे कार्य करते",
    dashboard: "डॅशबोर्ड",
    login: "लॉगिन करा",
    register: "नोंदणी करा",
    logout: "लॉगआउट",
    backToHome: "मुख्यपृष्ठावर जा",
    locality: "स्थान",
    profile: "माझे प्रोफाईल",

    // Dashboard Sidebar Items
    overview: "विहंगावलोकन",
    gisDashboard: "जीआयएस नकाशा",
    weatherMonitoring: "हवामान अंदाज",
    satelliteMonitoring: "उपग्रह निरीक्षण",
    soilHealth: "माती आरोग्य (मृदा)",
    pestSurveillance: "एआय कीड व रोग निदान",
    govSchemes: "शासकीय योजना",
    marketIntelligence: "बाजारभाव (मंडी)",
    farmerAdvisory: "शेतकरी सल्ला",

    // Page Titles & Descriptions
    dashTitle: "एकीकृत कृषी डॅशबोर्ड",
    dashDesc: "थेट माहिती व निर्णय समर्थन —",
    weatherTitle: "हवामान निरीक्षण व अंदाज",
    weatherDesc: "थेट स्थानिक हवामान आणि ७ दिवसांचा कृषी अंदाज —",
    soilTitle: "माती आरोग्य व अन्नद्रव्ये",
    soilDesc: "मातीची रासायनिक स्थिती, NPK पोषण, ओलावा आणि खत नियोजन —",
    advisoryTitle: "शेतकरी सल्ला व निर्णय सहाय्य",
    advisoryDesc: "हवामान, माती आणि बाजारभावानुसार तयार केलेला कृषी तज्ज्ञ सल्ला —",
    gisTitle: "जीआयएस व नकाशा प्रणाली",
    gisDesc: "स्थानिक शेतीचे उपग्रह नकाशे आणि जमिनीची माहिती —",
    satelliteTitle: "उपग्रह निरीक्षण व पीक निर्देशांक",
    satelliteDesc: "Sentinel-2 उपग्रहाद्वारे NDVI पीक आरोग्य आणि ओलावा निर्देशांक —",
    pestTitle: "एआय कीड व रोग निदान",
    pestDesc: "झाडाच्या पानाचा फोटो काढून तात्काळ रोग निदान व औषध फवारणी उपाय मिळवा.",
    schemesTitle: "शासकीय कृषी योजना व सबसिडी",
    schemesDesc: "केंद्र व महाराष्ट्र शासनाच्या सर्व अनुदान, पीक विमा व कर्ज योजनांची माहिती.",
    marketTitle: "बाजारभाव व कृषी सेवा केंद्र दर",
    marketDesc: "थेट कृषी उत्पन्न बाजार समिती भाव आणि खते, बियाणे, औषधांचे दर.",

    // Weather & Metrics
    ambientConditions: "सद्य परिस्थिती",
    humidity: "हवेतील आर्द्रता",
    windSpeed: "वाऱ्याचा वेग",
    precipitation: "पडलेला पाऊस",
    weatherCode: "हवामान कोड",
    synopticForecast: "📅 पुढील ७ दिवसांचा कृषी हवामान अंदाज",
    weatherSignals: "⚠️ स्वयंचलित कृषी हवामान संकेत",
    sprayFavorable: "✅ फवारणीस अनुकूल: वारा मंद असून पावसाची शक्यता नाही.",
    sprayWarning: "⚠️ फवारणी टाळा: जोरदार वारे किंवा पावसाचा अंदाज.",
    irrigationRecommended: "💧 पाणी देणे आवश्यक: गेल्या २४ तासांत पाऊस नाही.",
    soilMoistureSufficient: "✅ मातीत पुरेसा ओलावा: अति सिंचन टाळा.",

    // Soil
    soilIndex: "एकूण माती आरोग्य निर्देशांक",
    soilClassification: "जमिनीचा प्रकार",
    physicalProperties: "💧 भौतिक गुणधर्म",
    chemicalProperties: "⚗️ रासायनिक गुणधर्म",
    primaryNutrients: "🧪 मुख्य अन्नद्रव्ये (NPK)",
    organicCarbon: "सेंद्रिय कर्ब (SOC)",
    soilRecommendations: "💡 कृषी तज्ज्ञांचा माती सुधारणा सल्ला",
    nitrogen: "उपलब्ध नत्र (N)",
    phosphorus: "उपलब्ध स्फुरद (P)",
    potassium: "उपलब्ध पालाश (K)",
    phLevel: "सामू (pH)",

    // Market & Store
    apmcRates: "बाजार समिती (मंडी) दर",
    inputStore: "कृषी इनपुट केंद्र",
    fertilizers: "खते",
    seeds: "बियाणे",
    pesticides: "कीटकनाशके",
    priceComparison: "दुकान दर तुलना",
    minPrice: "किमान दर",
    maxPrice: "कमाल दर",
    modalPrice: "सरासरी दर",

    // Advisories
    activeAdvisories: "सक्रिय शेती सल्ले",
    rerunEngine: "🔄 सल्ले अद्यतनित करा",
    synthesizing: "⚙️ विश्लेषण सुरू आहे...",
    highPriority: "तातडीचा सल्ला",
    mediumPriority: "मध्यम प्राधान्य",
    lowPriority: "सामान्य सल्ला",

    // Schemes
    searchSchemes: "योजना किंवा लाभाचे नाव शोधा (उदा. किसान, सौर, ठिबक, ट्रॅक्टर)...",
    allCategories: "सर्व वर्गवारी",
    visitPortal: "अधिकृत पोर्टल ↗",
    benefits: "योजनेचे लाभ",
    eligibility: "पात्रता निकष",

    // Pest
    uploadPhoto: "पानाचा फोटो अपलोड करा",
    analyzeImage: "🔍 रोग निदान करा",
    pestDiagnosis: "एआय निदान निकाल",
    severity: "तीव्रता",
    treatmentPlan: "उपाययोजना व फवारणी",

    // Common
    temperature: "तापमान",
    soilMoisture: "मातीतील ओलावा",
    cropHealth: "पिकांचे आरोग्य",
    search: "शोधा",
    filter: "फिल्टर",
    status: "स्थिती",
    refresh: "ताजे करा",
    applyNow: "अधिकृत पोर्टल",
    loadingMsg: "माहिती लोड होत आहे...",
    retry: "पुन्हा प्रयत्न करा",

    // GIS & Spatial Map
    gisDashboardHeader: "कृषी समाधान जीआयएस डॅशबोर्ड",
    gisSubTitle: "परस्परसंवादी शेती नकाशा • ७-स्तरीय स्थानिक बुद्धिमत्ता —",
    gisArchitectureBtn: "७-स्तरीय आर्किटेक्चर",
    activeAlertsCount: "३ सक्रिय इशारे",
    farmerLabel: "शेतकरी",
    locationCadastre: "स्थान व भूमी अभिलेख",
    sync10m: "१०मी सिंक",
    spatialMapLayers: "स्थानिक नकाशा स्तर (लेयर्स)",
    activeCount: "सक्रिय",
    layerFarmBoundaries: "शेताच्या सीमा (गट/बांध)",
    layerCropTypes: "पिकांचे प्रकार व अवस्था",
    layerSatelliteHealth: "उपग्रह NDVI पीक आरोग्य",
    layerWaterCanals: "पाणी, कालवे व विहिरी",
    layerRainfallRadar: "पाऊस रडार",
    layerSoilNutrients: "मातीचे पोषण (NPK)",
    layerPestAlerts: "कीड व रोग प्रादुर्भाव क्षेत्र",
    layerMandis: "बाजार समिती (मंडी) व दर",
    layerIotSensors: "IoT सेन्सर नोड्स",
    filterPlots: "प्लॉट फिल्टर करा",
    crop: "पीक",
    allCrops: "सर्व पिके",
    riskLevel: "धोका पातळी",
    allRisks: "सर्व स्तर",
    highRisk: "उच्च धोका",
    mediumRisk: "मध्यम धोका",
    lowRisk: "कमी / सुरक्षित",
    surveyNo: "गट क्रमांक",
    owner: "शेतकरी",
    area: "क्षेत्रफळ",
    acres: "एकर",
    ndviHealth: "NDVI आरोग्य",
    estimatedYield: "अपेक्षित उत्पादन",
    agronomicDirective: "कृषी सल्लागार सूचना",
    aiAdvice: "एआय सल्ला",
    sendAlertSms: "इशारा SMS पाठवा",
    stage: "अवस्था",
    waterSource: "पाण्याचा स्रोत",
    yieldForecast: "उत्पादन अंदाज",
    discharge: "विसर्ग",
    capacityYield: "क्षमता / प्रवाह",
    highSeverityHotspot: "तीव्र प्रादुर्भाव क्षेत्र",
    distance: "अंतर",
    liveTradingRates: "थेट बाजार भाव",
    soilMoisture10cm: "मातीतील ओलावा (१० सेमी)",
    soilTemp: "मातीचे तापमान",
    leafWetness: "पानावरील ओलावा",
    solarBattery: "सोलर बॅटरी",
    lastPing: "सिग्नल",
    farmCoreCenter: "फार्म मुख्य केंद्र",
    clickReposition: "स्थान बदलण्यासाठी नकाशावर कुठेही क्लिक करा",
    spatialLegend: "नकाशा सूची (Legend)",
    legendHealthy: "उत्तम पीक आरोग्य (NDVI > ०.७०)",
    legendModerate: "मध्यम ताण / प्लॉट",
    legendHighRisk: "उच्च धोका / कीड प्रादुर्भाव क्षेत्र",
    legendCanal: "सक्रिय सिंचन कालवा नेटवर्क",
    baseMapSatellite: "🛰️ उपग्रह प्रतिमा",
    baseMapStreet: "🗺️ रस्ता नकाशा",
    baseMapTopo: "🏔️ स्थलाकृतिक (टोपो)",
    baseMapDark: "🌙 गडद भूप्रदेश",
    gisArchTitle: "७-स्तरीय कृषी जीआयएस आर्किटेक्चर",
    gisArchSubtitle: "विविध सेन्सर्सच्या डेटापासून ते स्थानिक शेतकरी कृतीपर्यंतची संपूर्ण प्रणाली.",
    gisL1Title: "१. डेटा स्रोत (Data Sources)",
    gisL1Desc: "हवामान API + Sentinel-2 उपग्रह + IoT माती सेन्सर्स + भूजल + पीक माहिती + मंडी भाव + शासकीय योजना.",
    gisL2Title: "२. डेटा एकत्रीकरण स्तर (Integration)",
    gisL2Desc: "अवकाशीय ETL इंजिन, समन्वय प्रक्षेपण (EPSG:4326), सेन्सर फिल्टरिंग आणि उपग्रह रास्टर प्रक्रिया.",
    gisL3Title: "३. जीआयएस स्तर (GIS Spatial)",
    gisL3Desc: "शेत सीमा (गट क्रमांक), सिंचन कालवे, थर्मल थर आणि बाजार समिती जिओ-टॅगिंग.",
    gisL4Title: "४. एआय आणि विश्लेषण स्तर (AI / Analytics)",
    gisL4Desc: "पीक जल ताण निर्देशांक (CWSI), कीड प्रसार मॉडेल, हवामान धोका आणि उत्पादन अंदाज अल्गोरिदम.",
    gisL5Title: "५. निर्णय समर्थन स्तर (Decision Support)",
    gisL5Desc: "सर्व डेटाचे कृषी प्राधान्यक्रम आणि तात्काळ कृती उपायांमध्ये रूपांतर करणारी नियम प्रणाली.",
    gisL6Title: "६. शेतकरी सल्ला स्तर (Farmer Advisory)",
    gisL6Desc: "मराठी, हिंदी आणि इंग्रजी भाषेत शेतकऱ्यांसाठी सुलभ व कृतीयोग्य मार्गदर्शन.",
    gisL7Title: "७. डॅशबोर्ड व सूचना स्तर (Dashboard & Alerts)",
    gisL7Desc: "परस्परसंवादी नकाशा, थेट इशारा केंद्र, SMS/व्हॉट्सॲप सूचना आणि त्वरित उपाययोजना.",
    closeExplorer: "आर्किटेक्चर विंडो बंद करा",
    smsSentToast: "इशारा SMS यशस्वीरित्या पाठवला —",

    // Satellite Monitoring
    satelliteLoading: "उपग्रह स्पेक्ट्रल प्रतिमा (Sentinel-2) प्रक्रिया सुरू आहे —",
    satelliteError: "उपग्रह माहिती मिळवण्यात अडचण आली.",
    livePass: "थेट पास",
    sentinelTelemetry: "Sentinel-2 उपग्रह माहिती:",
    sentinelSub: "१० मीटर रिझोल्यूशनवरील पृष्ठभाग परावर्तन —",
    ndviVigorIndex: "NDVI पीक जोम निर्देशांक",
    canopyMoisture: "पानांमधील ओलावा (NDWI)",
    cropStressRisk: "पीक ताण धोका",
    cloudCover: "ढगांचे प्रमाण",
    adequateHydration: "पुरेसा ओलावा उपलब्ध",
    zeroThermalAnomalies: "कोणतीही थर्मल समस्या नाही",
    opticalClarity: "स्पष्ट उपग्रह दृश्य",
    minimalOptimal: "अतिशय कमी (उत्तम)",
    moderate: "मध्यम",
    landCoverUse: "जमिनीचा वापर व आच्छादन",
    activeCropland: "सक्रिय लागवड क्षेत्र",
    treeCoverOrchards: "झाडे व फळबागा",
    ruralSettlement: "वस्ती / रस्ते",
    farmPonds: "शेततळी / जलसाठे",
    biomassTrend: "बायोमास कल व कृषी सारांश",
    photosyntheticBiomass: "+६.८% प्रकाशसंश्लेषण बायोमास वाढ",
    sensorInfo: "सेन्सर: Sentinel-2 MSI • निरभ्र आकाश",
    healthy: "निरोगी / उत्तम",

    // Chatbot
    chatTitle: "कृषी AI सहाय्यक",
    chatSubtitle: "सक्रिय कृषी सल्लागार",
    chatPlaceholder: "मराठी, हिंदी किंवा इंग्रजीत विचारा...",
    chatLauncher: "कृषी AI ला विचारा",
    chatGreeting: "नमस्कार! 🙏 मी कृषी AI, आपला कृषी समाधान सहाय्यक आहे. हवामान, मातीचे आरोग्य, खतांचे प्रमाण, कीड नियंत्रण किंवा बाजारभावाबद्दल काहीही विचारा!",
    sugWeather: "🌦️ स्थानिक हवामान",
    sugSoil: "🌱 खत व माती मार्गदर्शन",
    sugPest: "🐛 कीड नियंत्रण उपाय",
    sugMandi: "💰 आजचे बाजारभाव",
    sugSchemes: "🏛️ नमो शेतकरी योजना"
  },

  hi: {
    // Brand & Global
    brandName: "कृषि समाधान",
    tagline: "सटीक निर्णय. समृद्ध खेती.",
    heroTitle1: "सटीक निर्णय.",
    heroTitle2: "समृद्ध खेती.",
    heroTagline: "बेहतर जानकारी। सटीक निर्णय। बेहतर खेती।",
    heroSubtitle: "मिट्टी से लेकर आसमान तक, फसल के स्वास्थ्य से लेकर मंडी भाव तक — सही निर्णय लेने और आत्मविश्वास के साथ आगे बढ़ने के लिए जरूरी हर जानकारी एक ही मंच पर।",
    explorePlatform: "मंच देखें",
    learnMore: "और जानें",
    activeStream: "सक्रिय स्ट्रीम",
    monitoringLocality: "निगरानी क्षेत्र",

    // Navigation
    home: "होम",
    features: "विशेषताएं",
    howItWorks: "यह कैसे काम करता है",
    dashboard: "डैशबोर्ड",
    login: "लॉग इन",
    register: "खाता बनाएं",
    logout: "लॉग आउट",
    backToHome: "होम पर वापस जाएं",
    locality: "स्थान",
    profile: "मेरी प्रोफ़ाइल",

    // Dashboard Sidebar Items
    overview: "अवलोकन",
    gisDashboard: "जीआईएस मानचित्र",
    weatherMonitoring: "मौसम निगरानी",
    satelliteMonitoring: "उपग्रह निगरानी",
    soilHealth: "मृदा स्वास्थ्य (मिट्टी)",
    pestSurveillance: "एआई कीट व रोग निदान",
    govSchemes: "सरकारी योजनाएं",
    marketIntelligence: "मंडी भाव",
    farmerAdvisory: "किसान सलाह",

    // Page Titles & Descriptions
    dashTitle: "एकीकृत कृषि डैशबोर्ड",
    dashDesc: "लाइव डेटा और निर्णय सहायता —",
    weatherTitle: "मौसम निगरानी एवं पूर्वानुमान",
    weatherDesc: "वास्तविक समय मौसम और 7-दिवसीय कृषि पूर्वानुमान —",
    soilTitle: "मृदा स्वास्थ्य एवं पोषण प्रबंधन",
    soilDesc: "मिट्टी की रसायन, NPK पोषक तत्व, नमी और खाद अनुशंसाएं —",
    advisoryTitle: "किसान सलाह एवं निर्णय सहायता",
    advisoryDesc: "मौसम, मिट्टी और मंडी भाव के आधार पर कृषि वैज्ञानिकों की सलाह —",
    gisTitle: "जीआईएस एवं स्थानिक मानचित्र",
    gisDesc: "खेतों का सैटेलाइट नक्शा और भू-स्थानिक डेटा —",
    satelliteTitle: "उपग्रह निगरानी एवं फसल सूचकांक",
    satelliteDesc: "Sentinel-2 उपग्रह द्वारा NDVI फसल स्वास्थ्य और नमी सूचकांक —",
    pestTitle: "एआई फसल कीट एवं रोग पहचान",
    pestDesc: "पत्ती की तस्वीर खींचकर तुरंत रोग पहचान और सटीक उपचार योजना पाएं।",
    schemesTitle: "सरकारी कृषि योजनाएं एवं सब्सिडी",
    schemesDesc: "केंद्र एवं राज्य सरकार की सभी सब्सिडी, बीमा और ऋण योजनाओं की जानकारी।",
    marketTitle: "मंडी भाव एवं कृषि स्टोर दरें",
    marketDesc: "लाइव APMC मंडी भाव एवं खाद, बीज, कीटनाशक दुकानों के रेट।",

    // Weather & Metrics
    ambientConditions: "वर्तमान मौसम स्थिति",
    humidity: "सापेक्ष आर्द्रता",
    windSpeed: "हवा की गति",
    precipitation: "वर्षा मात्रा",
    weatherCode: "मौसम कोड",
    synopticForecast: "📅 7-दिवसीय कृषि मौसम पूर्वानुमान",
    weatherSignals: "⚠️ स्वचालित कृषि मौसम संकेत",
    sprayFavorable: "✅ छिड़काव के लिए अनुकूल: शांत हवा और बारिश की संभावना नहीं।",
    sprayWarning: "⚠️ छिड़काव टालें: तेज हवा या बारिश की चेतावनी।",
    irrigationRecommended: "💧 सिंचाई की सिफारिश: पिछले 24 घंटों में बारिश नहीं हुई।",
    soilMoistureSufficient: "✅ मिट्टी में पर्याप्त नमी: अतिरिक्त सिंचाई न करें।",

    // Soil
    soilIndex: "समग्र मृदा स्वास्थ्य सूचकांक",
    soilClassification: "मिट्टी का वर्गीकरण",
    physicalProperties: "💧 भौतिक गुण",
    chemicalProperties: "⚗️ रासायनिक गुण",
    primaryNutrients: "🧪 मुख्य पोषक तत्व (NPK)",
    organicCarbon: "जैविक कार्बन (SOC)",
    soilRecommendations: "💡 कृषि वैज्ञानिक मृदा सुधार सिफारिशें",
    nitrogen: "उपलब्ध नाइट्रोजन (N)",
    phosphorus: "उपलब्ध फास्फोरस (P)",
    potassium: "उपलब्ध पोटाश (K)",
    phLevel: "पीएच मान (pH)",

    // Market & Store
    apmcRates: "मंडी (APMC) भाव",
    inputStore: "कृषि इनपुट स्टोर",
    fertilizers: "खाद/उर्वरक",
    seeds: "बीज",
    pesticides: "कीटनाशक",
    priceComparison: "दुकान मूल्य तुलना",
    minPrice: "न्यूनतम भाव",
    maxPrice: "अधिकतम भाव",
    modalPrice: "औसत / मॉडल भाव",

    // Advisories
    activeAdvisories: "सक्रिय किसान सलाह",
    rerunEngine: "🔄 सलाह अपडेट करें",
    synthesizing: "⚙️ विश्लेषण जारी है...",
    highPriority: "उच्च प्राथमिकता",
    mediumPriority: "मध्यम प्राथमिकता",
    lowPriority: "सामान्य सलाह",

    // Schemes
    searchSchemes: "योजना या लाभ का नाम खोजें (जैसे किसान, सोलर, ड्रिप, ट्रैक्टर)...",
    allCategories: "सभी श्रेणियां",
    visitPortal: "आधिकारिक पोर्टल ↗",
    benefits: "योजना के लाभ",
    eligibility: "पात्रता",

    // Pest
    uploadPhoto: "पत्ती की तस्वीर अपलोड करें",
    analyzeImage: "🔍 रोग की जांच करें",
    pestDiagnosis: "एआई जांच परिणाम",
    severity: "गंभीरता",
    treatmentPlan: "सटीक उपचार योजना",

    // Common
    temperature: "तापमान",
    soilMoisture: "मिट्टी की नमी",
    cropHealth: "फसल स्वास्थ्य",
    search: "खोजें",
    filter: "फ़िल्टर",
    status: "स्थिति",
    refresh: "रिफ्रेश",
    applyNow: "आधिकारिक पोर्टल",
    loadingMsg: "डेटा लोड हो रहा है...",
    retry: "पुनः प्रयास करें",

    // GIS & Spatial Map
    gisDashboardHeader: "कृषि समाधान जीआईएस डैशबोर्ड",
    gisSubTitle: "इंटरएक्टिव कृषि मानचित्र • 7-स्तरीय स्थानिक बुद्धिमत्ता —",
    gisArchitectureBtn: "7-स्तरीय आर्किटेक्चर",
    activeAlertsCount: "3 सक्रिय अलर्ट",
    farmerLabel: "किसान",
    locationCadastre: "स्थान एवं भू-अभिलेख",
    sync10m: "10मी सिंक",
    spatialMapLayers: "स्थानिक मानचित्र परतें (लेयर्स)",
    activeCount: "सक्रिय",
    layerFarmBoundaries: "खेत की सीमाएं (मेड़/पार्सल)",
    layerCropTypes: "फसल के प्रकार और अवस्था",
    layerSatelliteHealth: "उपग्रह NDVI फसल स्वास्थ्य",
    layerWaterCanals: "जल स्रोत, नहरें एवं कुएं",
    layerRainfallRadar: "वर्षा रडार",
    layerSoilNutrients: "मृदा पोषण (NPK)",
    layerPestAlerts: "कीट व रोग प्रकोप क्षेत्र",
    layerMandis: "मंडी (APMC) एवं भाव",
    layerIotSensors: "IoT सेंसर नोड्स",
    filterPlots: "खेत फ़िल्टर करें",
    crop: "फसल",
    allCrops: "सभी फसलें",
    riskLevel: "जोखिम स्तर",
    allRisks: "सभी स्तर",
    highRisk: "उच्च जोखिम",
    mediumRisk: "मध्यम जोखिम",
    lowRisk: "कम / सुरक्षित",
    surveyNo: "खसरा / सर्वे नं",
    owner: "मालिक",
    area: "क्षेत्रफल",
    acres: "एकड़",
    ndviHealth: "NDVI स्वास्थ्य",
    estimatedYield: "अनुमानित उपज",
    agronomicDirective: "कृषि वैज्ञानिक निर्देश",
    aiAdvice: "एआई सलाह",
    sendAlertSms: "अलर्ट SMS भेजें",
    stage: "अवस्था",
    waterSource: "जल स्रोत",
    yieldForecast: "उपज पूर्वानुमान",
    discharge: "प्रवाह दर",
    capacityYield: "क्षमता / प्रवाह",
    highSeverityHotspot: "गंभीर प्रकोप क्षेत्र",
    distance: "दूरी",
    liveTradingRates: "लाइव मंडी भाव",
    soilMoisture10cm: "मिट्टी की नमी (10 सेमी)",
    soilTemp: "मिट्टी का तापमान",
    leafWetness: "पत्तियों की नमी",
    solarBattery: "सोलर बैटरी",
    lastPing: "पिंग",
    farmCoreCenter: "फार्म केंद्र बिंदु",
    clickReposition: "स्थान बदलने के लिए मानचित्र पर कहीं भी क्लिक करें",
    spatialLegend: "मानचित्र संकेत (Legend)",
    legendHealthy: "स्वस्थ फसल (NDVI > 0.70)",
    legendModerate: "मध्यम तनाव वाले खेत",
    legendHighRisk: "उच्च जोखिम / कीट प्रकोप क्षेत्र",
    legendCanal: "सक्रिय सिंचाई नहर नेटवर्क",
    baseMapSatellite: "🛰️ सैटेलाइट इमेज",
    baseMapStreet: "🗺️ साधारण सड़क",
    baseMapTopo: "🏔️ स्थलाकृतिक",
    baseMapDark: "🌙 डार्क टेरेन",
    gisArchTitle: "7-स्तरीय कृषि जीआईएस आर्किटेक्चर",
    gisArchSubtitle: "विभिन्न सेंसर डेटा स्रोतों से लेकर किसान के खेत तक की संपूर्ण प्रणाली।",
    gisL1Title: "1. डेटा स्रोत (Data Sources)",
    gisL1Desc: "मौसम API + Sentinel-2 उपग्रह + IoT मृदा सेंसर + भूजल + फसल डेटा + मंडी भाव + सरकारी योजनाएं।",
    gisL2Title: "2. डेटा एकीकरण परत (Integration)",
    gisL2Desc: "स्थानिक ईटीएल इंजन, समन्वय प्रक्षेपण (EPSG:4326), सेंसर फ़िल्टरिंग और सैटेलाइट रास्टर प्रोसेसिंग।",
    gisL3Title: "3. जीआईएस परत (GIS Spatial)",
    gisL3Desc: "खेत की सीमाएं (खसरा संख्या), सिंचाई नहरें, थर्मल लेयर्स और मंडी जियो-टैगिंग।",
    gisL4Title: "4. एआई एवं एनालिटिक्स परत (AI / Analytics)",
    gisL4Desc: "फसल जल तनाव सूचकांक (CWSI), कीट प्रसार मॉडल, मौसम जोखिम और उपज पूर्वानुमान एल्गोरिदम।",
    gisL5Title: "5. निर्णय सहायता परत (Decision Support)",
    gisL5Desc: "सभी डेटा को कृषि प्राथमिकताओं और त्वरित उपायों में बदलने वाला नियम इंजन।",
    gisL6Title: "6. किसान सलाह परत (Farmer Advisory)",
    gisL6Desc: "मराठी, हिंदी और अंग्रेजी में किसानों के लिए सरल एवं व्यावहारिक निर्देश।",
    gisL7Title: "7. डैशबोर्ड एवं अलर्ट परत (Dashboard & Alerts)",
    gisL7Desc: "इंटरएक्टिव मानचित्र, लाइव अलर्ट केंद्र, एसएमएस/व्हाट्सएप सूचनाएं और त्वरित समाधान।",
    closeExplorer: "आर्किटेक्चर विंडो बंद करें",
    smsSentToast: "अलर्ट SMS सफलतापूर्वक भेजा गया —",

    // Satellite Monitoring
    satelliteLoading: "उपग्रह स्पेक्ट्रल इमेजरी (Sentinel-2) प्रोसेस हो रही है —",
    satelliteError: "उपग्रह डेटा प्राप्त करने में विफल।",
    livePass: "लाइव पास",
    sentinelTelemetry: "Sentinel-2 सैटेलाइट डेटा:",
    sentinelSub: "10 मीटर रिज़ॉल्यूशन पर सतह परावर्तन —",
    ndviVigorIndex: "NDVI फसल स्वास्थ्य सूचकांक",
    canopyMoisture: "पत्तियों में नमी (NDWI)",
    cropStressRisk: "फसल तनाव जोखिम",
    cloudCover: "बादलों का आवरण",
    adequateHydration: "पर्याप्त नमी उपलब्ध",
    zeroThermalAnomalies: "कोई थर्मल विसंगति नहीं",
    opticalClarity: "स्पष्ट उपग्रह दृश्य",
    minimalOptimal: "न्यूनतम (उत्तम)",
    moderate: "मध्यम",
    landCoverUse: "भूमि उपयोग एवं आवरण",
    activeCropland: "सक्रिय फसली क्षेत्र",
    treeCoverOrchards: "वृक्ष एवं फलदार बाग",
    ruralSettlement: "ग्रामीण बस्ती / सड़कें",
    farmPonds: "खेत तालाब / जल संचयन",
    biomassTrend: "बायोमास प्रवृत्ति एवं कृषि सारांश",
    photosyntheticBiomass: "+6.8% प्रकाश संश्लेषण बायोमास",
    sensorInfo: "सेंसर: Sentinel-2 MSI • बादल रहित दृश्य",
    healthy: "स्वस्थ / उत्तम",

    // Chatbot
    chatTitle: "कृषि AI सहायक",
    chatSubtitle: "सक्रिय निर्णय सहायता",
    chatPlaceholder: "हिंदी, मराठी या अंग्रेजी में पूछें...",
    chatLauncher: "कृषि AI से पूछें",
    chatGreeting: "नमस्ते! 🙏 मैं कृषि AI हूँ, आपका कृषि समाधान सहायक। मौसम, खाद, कीट नियंत्रण, मंडी भाव या सरकारी योजनाओं के बारे में कुछ भी पूछें!",
    sugWeather: "🌦️ आज का मौसम",
    sugSoil: "🌱 खाद और मिट्टी सलाह",
    sugPest: "🐛 कीट नियंत्रण उपाय",
    sugMandi: "💰 आज का मंडी भाव",
    sugSchemes: "🏛️ पीएम किसान योजना"
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguageState] = useState(() => {
    return localStorage.getItem('agri_lang') || 'en';
  });

  const setLanguage = (lang) => {
    if (['en', 'mr', 'hi'].includes(lang)) {
      setLanguageState(lang);
      localStorage.setItem('agri_lang', lang);
    }
  };

  const t = (key) => {
    const langDict = translations[language] || translations.en;
    return langDict[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);

export default LanguageContext;
